[package]
name = "del-msh-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
rand = { workspace = true }
num-traits = { workspace = true }
nalgebra = { workspace = true }
ordered-float = { workspace =true }
del-geo = {workspace = true}