[workspace]
members = [
    "del-msh-pyo3",
    "del-msh-core"
]
resolver = "2"

[workspace.package]
version = "0.1.33"
edition = "2021"
authors = ["Nobuyuki Umetani <n.umetani@gmail.com>"]
license = "MIT"
repository = "https://github.com/nobuyuki83/del-msh/"
description = "mesh utility library for computer graphics research and prototyping"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
rand = "0.8.5"
ordered-float = "4.2.1"
num-traits = "0.2.19"
nalgebra = "0.33.0"
del-geo = {path="../del-geo"}
# del-geo = "0.1.29"
del-msh = { path = "./del-msh-core", package = "del-msh-core" }