[package]
name = "del-msh"
version = "0.1.12"
edition = "2021"
authors = ["Nobuyuki Umetani <n.umetani@gmail.com>"]
license = "MIT"
repository = "https://github.com/nobuyuki83/del-msh/"
description = "mesh utility library for computer graphics research"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.16"
nalgebra = "0.32.3"
# del-geo = {path="../del-geo"}
del-geo = "0.1.5"