[package]
name = "del-msh"
version = "0.1.0"
edition = "2022"
authors = ["Nobuyuki Umetani <n.umetani@gmail.com>"]
license = "MIT"
description = "mesh library for computer graphics research"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.15"
